# CBOM Demo PostgreSQL Client Authentication
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Local connections
local   all             all                                     scram-sha-256

# IPv4 local connections with SSL required
hostssl all             all             0.0.0.0/0               scram-sha-256
hostssl all             all             127.0.0.1/32            scram-sha-256

# IPv6 local connections with SSL required
hostssl all             all             ::1/128                 scram-sha-256

# Allow non-SSL for demo purposes (Zeek can detect both)
host    all             all             0.0.0.0/0               scram-sha-256
